# github action for automatically merging PRs opened by kong-apiops

name: Auto Merge

on:
  pull_request:
    types: [opened]
    # branch must be automated-update
    branches: [automated-update]
    
jobs:

  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'kong-apiops' }}}
    steps:
      - uses: actions/checkout@v2
      - uses:
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          merge-label: auto-merge
          
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
            
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              name: 'auto-merge'
            })
            
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: 'Pull request has been merged successfully.'
            })
            
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['merged']
            })
            
      
