name: Generate SDK Packages
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  contents: write
jobs:
  get-changed-files:
    name: Get Changed Files
    runs-on: ubuntu-latest
    outputs:
      oas-modified: ${{ steps.oas-modified.outputs.any_modified }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if `openapi.yaml` has changed
        uses: tj-actions/changed-files@4edd678ac3f81e2dc578756871e4d00c19191daf
        id: oas-modified
        with:
          files: |
            openapi.yaml
  generate-js:
    name: Generate JavaScript SDK
    runs-on: ubuntu-latest
    needs: [get-changed-files]
    if: needs.get-changed-files.outputs.oas-modified == 'true'
    env:
      changes_exist: false
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.ref }}
          path: actions
          token: ${{ secrets.API_OPS_GH_PAT }}

      - name: Build JavaScript SDK
        uses: Kong/public-shared-actions/code-build-actions/build-js-sdk@main
        with:
          app_directory: ${{ github.workspace }}
          sdk_output_directory: ${{ github.workspace }}/actions
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check if SDK output has changed
        shell: bash
        working-directory: ${{ github.workspace }}/actions
        env:
          GH_TOKEN: ${{ secrets.PORTAL_JS_SDK_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          
          if git diff --exit-code src; then
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "changes_exist=true" >> $GITHUB_ENV
          fi
      - name: Commit SDK changes to the PR
        if: ${{ env.changes_exist == 'true' }}
        shell: bash
        working-directory: ${{ github.workspace }}/actions
        env:
          GH_TOKEN: ${{ secrets.PORTAL_JS_SDK_TOKEN }}
        run: |
          git config --global user.email "team-devx+github-bot@konghq.com"
          git config --global user.name "team-devx"
          gh pr checkout ${{ github.event.pull_request.number }}
          git add src/
          git commit -m "chore: build SDK from openapi.yaml changes"
          git push
