name: Generate SDK Packages
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  contents: write
jobs:
  generate-js:
    name: Generate JavaScript SDK
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.ref }}
          path: actions

      - name: Build JavaScript SDK
        uses: Kong/public-shared-actions/code-build-actions/build-js-sdk@v1.11.0
        with:
          app_directory: ${{ github.workspace }}
          sdk_output_directory: ${{github.workspace}}/sdk
          token: ${{secrets.GITHUB_TOKEN}}
