name: Generate SDK Packages
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  contents: write
jobs:
  generate-js:
    name: Generate JavaScript SDK
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.ref }}
          path: actions

      - name: Build JavaScript SDK
        uses: andrewwylde/public-shared-actions/code-build-actions/build-js-sdk@9a1483670e976163a295252253d4b859c80d419e
        with:
          app_directory: ${{ github.workspace }}
          sdk_output_directory: ${{ github.workspace }}/actions
          token: ${{secrets.GITHUB_TOKEN}}
