name: Release

on: [push]

permissions: 
  # Needed to create PR statuses/checks
  checks: write
  statuses: write
  # Needed to push git tags, release
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROTECTED_BRANCH_REVIEWER_TOKEN: ${{ secrets.PORTAL_JS_SDK_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_PRIVATE_PUBLISH }}
        run: |
          yarn install --frozen-lockfile
          yarn build
          npx auto shipit -vv
